-- =============================================================================
-- Controle de Psicotrópicos — Esquema Oracle (12.1 ou superior)
-- Executar conectado como o USUÁRIO DONO DAS TABELAS (ex.: PSICO_OWNER).
-- =============================================================================
-- Convenções:
--  * Horários em UTC, gravados pela aplicação (TIMESTAMP sem fuso).
--  * Nenhum registro é apagado: exclusões são lógicas (colunas excluido_em/...).
--  * Texto em semântica CHAR para suportar acentuação sem estourar o limite.
-- =============================================================================

CREATE TABLE usuarios (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login              VARCHAR2(100 CHAR)  NOT NULL,
  nome               VARCHAR2(200 CHAR)  NOT NULL,
  senha_hash         VARCHAR2(100 CHAR)  NOT NULL,
  papel              VARCHAR2(20 CHAR)   DEFAULT 'funcionario' NOT NULL,
  ativo              NUMBER(1)           DEFAULT 1 NOT NULL,
  tentativas_falhas  NUMBER(5)           DEFAULT 0 NOT NULL,
  bloqueado_ate      TIMESTAMP(0),
  deve_trocar_senha  NUMBER(1)           DEFAULT 0 NOT NULL,
  sessao_versao      NUMBER(10)          DEFAULT 1 NOT NULL,
  senha_alterada_em  TIMESTAMP(0),
  ultimo_login_em    TIMESTAMP(0),
  criado_em          TIMESTAMP(0)        DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT uq_usuarios_login UNIQUE (login),
  CONSTRAINT ck_usuarios_papel CHECK (papel IN ('admin', 'funcionario')),
  CONSTRAINT ck_usuarios_ativo CHECK (ativo IN (0, 1))
);

CREATE TABLE setores (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome               VARCHAR2(200 CHAR)  NOT NULL,
  ativo              NUMBER(1)           DEFAULT 1 NOT NULL,
  excluido_em        TIMESTAMP(0),
  excluido_por_nome  VARCHAR2(200 CHAR),
  criado_em          TIMESTAMP(0)        DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT uq_setores_nome UNIQUE (nome)
);

CREATE TABLE anestesistas (
  codigo_cracha      VARCHAR2(100 CHAR)  PRIMARY KEY,
  nome               VARCHAR2(200 CHAR)  NOT NULL,
  crm                VARCHAR2(30 CHAR),
  ativo              NUMBER(1)           DEFAULT 1 NOT NULL,
  excluido_em        TIMESTAMP(0),
  excluido_por_nome  VARCHAR2(200 CHAR),
  criado_em          TIMESTAMP(0)        DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL
);

CREATE TABLE dispensacoes (
  id                            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_anestesista            VARCHAR2(100 CHAR) NOT NULL,
  nome_anestesista              VARCHAR2(200 CHAR),
  codigo_caixa                  VARCHAR2(100 CHAR) NOT NULL,
  codigo_atendimento_paciente   VARCHAR2(100 CHAR) NOT NULL,
  setor_id                      NUMBER,
  setor_nome                    VARCHAR2(200 CHAR),
  kit_venoso                    NUMBER(1)          DEFAULT 0 NOT NULL,
  horario_entrega               TIMESTAMP(0)       NOT NULL,
  horario_devolucao             TIMESTAMP(0),
  status                        VARCHAR2(20 CHAR)  DEFAULT 'em_posse' NOT NULL,
  observacoes                   VARCHAR2(1000 CHAR),
  registrado_por_id             NUMBER,
  registrado_por_nome           VARCHAR2(200 CHAR),
  devolvido_por_id              NUMBER,
  devolvido_por_nome            VARCHAR2(200 CHAR),
  anestesista_devolucao_cracha  VARCHAR2(100 CHAR),
  anestesista_devolucao_nome    VARCHAR2(200 CHAR),
  excluido_em                   TIMESTAMP(0),
  excluido_por_id               NUMBER,
  excluido_por_nome             VARCHAR2(200 CHAR),
  motivo_exclusao               VARCHAR2(500 CHAR),
  criado_em                     TIMESTAMP(0)       DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  atualizado_em                 TIMESTAMP(0)       DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT ck_disp_status CHECK (status IN ('em_posse', 'devolvida')),
  CONSTRAINT ck_disp_kit CHECK (kit_venoso IN (0, 1))
);

CREATE TABLE historico_edicoes (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispensacao_id     NUMBER              NOT NULL,
  campo_alterado     VARCHAR2(100 CHAR)  NOT NULL,
  valor_anterior     VARCHAR2(1000 CHAR),
  valor_novo         VARCHAR2(1000 CHAR),
  editado_por_id     NUMBER,
  editado_por_nome   VARCHAR2(200 CHAR),
  alterado_em        TIMESTAMP(0)        DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT fk_hist_disp FOREIGN KEY (dispensacao_id) REFERENCES dispensacoes (id)
);

CREATE TABLE auditoria (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ocorrido_em        TIMESTAMP(0)        NOT NULL,
  usuario_id         NUMBER,
  usuario_login      VARCHAR2(100 CHAR),
  acao               VARCHAR2(60 CHAR)   NOT NULL,
  entidade           VARCHAR2(60 CHAR),
  entidade_id        VARCHAR2(100 CHAR),
  detalhes           VARCHAR2(2000 CHAR),
  ip                 VARCHAR2(64 CHAR)
);

CREATE INDEX idx_disp_anestesista ON dispensacoes (codigo_anestesista);
CREATE INDEX idx_disp_paciente    ON dispensacoes (codigo_atendimento_paciente);
CREATE INDEX idx_disp_caixa       ON dispensacoes (codigo_caixa);
CREATE INDEX idx_disp_data        ON dispensacoes (horario_entrega);
CREATE INDEX idx_disp_status      ON dispensacoes (status);
CREATE INDEX idx_disp_setor       ON dispensacoes (setor_id);
CREATE INDEX idx_hist_disp        ON historico_edicoes (dispensacao_id);
CREATE INDEX idx_aud_data         ON auditoria (ocorrido_em);
